* [[https://class.coursera.org/fog-001/lecture][Fog Networks and the Internet of Things]]

  http://www.gns3.com/
  
** Lecture 1: Fog Networking - Going from Cloud to Fog
*** DONE Part A (8:51)
    CLOSED: [2015-04-03 Fri 07:47]
*** DONE Part B (21:28)
    CLOSED: [2015-04-11 Sat 07:33] SCHEDULED: <2015-04-04 Sat>
    ▶ What is Fog network
    A network architecture that uses one or a collaborative multitude of 
    end-user clients (phones, laptops)
    or
    near-user edge devices (set-top boxes, Femto base stations, home gateways)
    to carry out a substantial (էական, nor 100% but substential amount of something) amount of
    1. storage  (rather than stored primarily in cloud data centers),
    2. communication (rather than routed over wide-area so called backbone networks), 
    3. control, configuration, measurement and management (rather than controlled primarily by network gateways such as those you can 
    find in the so-called core network of 4G LTE). 
    ▶ What is Fog network
    Is the architecture who describes
    * Who does What?
    * How to connect them?
    * Architecture - not allocating resources but allocating functions in network.
    And Fog network is an architecture that use could be just one 
    or 
    could be more than one that work with each other - thet is what we mean by collaborative multitude.
    

*** DONE Part C - Use Cases (8:29)
    CLOSED: [2015-04-15 Wed 07:04] SCHEDULED: <2015-04-11 Sat>
    [[http://www.sit-com.ru/femtocell-megafon-mts.html][Что такое фемтосота(Femtocell)?]]
    Use cases of fog networks
    ▶OTT Service Charging
    Clients can crowd-source network inference/measurement and overlay billing
    ▶Client-Side HetNets Control - Clients can autonomously manage/control their own configuration
    How car choose which line to go over 3 line?
    HetNets - Hetergeneous Networks
    WiFi AP - LTE
    RNS(eNodeB) - 
    HNS(Home Gateway, HomeNodeBN) - FemtoCell
    ▶Client Resource Pooling
    Idle resources on the edge pooled but shared unpredictably 
*** DONE Part D Fog as a Network Architecture (10:37)
    CLOSED: [2015-04-15 Wed 07:40] SCHEDULED: <2015-04-11 Sat>
    ▶Fog as network architecture
    5G, IoT, Big Data, EDD(Edge-driven "Data center"), EDC(Edge-Driven Control plane)
    
    ▶Examples
    • Over The Top (OTT) content management and SDP
    • Client-centric HetNets Control
    • Client-controlled cloudstorage
    • Session management and signaling load optimization
    • Crowd-sensing inference of network states
    • Edge analytics and real-time stream-mining
    • Clients’ idle computing/storage/content pooling
    • Edge caching/BW management at home gateway/small cell
    • FlashLinQ/LTE Direct/WiFiDirect/AirDrop
    • Cloudlets/Micro Datacenters/Mobile CDN
    • Client-driven distributed beam-forming(Проектирование фазированных антенных решёток) 
    ▶NFO - Network Function Optimization, there are several threads to rethinking
    • Redefine Network Functions - CCN(Content Centric Network) or ICN(Information Centric Network)
      Manipulating digital objects not packets, and this redefine a lot functions that we need to think about
    • Virtualize the network not just computing infrastructure- NFV(Network Function Virtualization)
    • Relocating the network functions - FOG

    ▶Research Challenges
    • Trustworthiness/ verification of client/edge software & hardware - Do I trust this cients or things or Edges?
    • Incentivization(Խթանել) of client participation - maybe they do not want to participate on resource pooling, crows-sourcing, 
      how do I Incentivization their participation?
    • Interactions w. client/IoT OS and definition of network service APIs
    • Interfaces: Cloud-to-cloud and cloud-to-fog
    • Oscillation/divergence and global configuration consistency during the interactions of local actions
    • Tradeoff of Local vs. Global architecture, Distributed vs. Centralized 
    •
    •
    ▶Inter-Disciplinary Solutions - http://fogresearch.org
    ▶Impact on Value Proposition along Ecosystem Food-chain
    • End user experience providers?
    • Network operators?
    • Equipment vendors?
    • Cloud service providers?
    • System integrators?
    • Edge device manufacturers?
    • Client/IoT device manufacturers/OS?
    • Chip suppliers? 
    
    
** Lecture 2: From IT(information technology) to IOT
*** DONE Part A (17:48) 
    CLOSED: [2015-04-16 Thu 07:47] SCHEDULED: <2015-04-16 Thu>
    5G, IoT, Big Data, EDD, EDC
    IoT = I & T
    • Internet
    - Connected
    • Things
    * Communicate (port or antenna)
    * Sense (sensors ...)
    * Actuate - cahnge something in environment(embedded controllers...)
    * Compute (processor)
    * Store (memory)
    * Interact (touchescreen)
   
   IoT Applications' Classification
   ▶Consumer oriented
   • Consumer & Wearable (virtual reallity devices, glasses, colothes)
   • Home & Building 
   
   ▶Industrial Oriented
   • Healthcare 
   • Vehicular & Transportation
   • Smart grids & Energy
   • City & Urban
   • Environment & Agriculture
   • Industrial & Logistics

*** DONE Part B (14:23) The heterogeneity of out IT application need, is a major chanllange that researchers in this filed have to tackle. 
    CLOSED: [2015-04-18 Sat 09:24] SCHEDULED: <2015-04-16 Thu>
    We should ask ourselves in this particular IoT application, What kind of energy, delay, throughput, 
    signaling cost, and human in the loop conditions are required.
    
    ▶Heterogeneous needs
    • Energy
    • Delay - 
    • Throughput  - has many order of magnitute variation within IoT applications.
    • Signaling overhead - 
    • Cost
    • Human in the loop
   
    ▶ IoT use cases requirements
    |                             | Smart meters(cities)          | eHealth                     | ITS*                               | Surveilance    |
    |                             |                               |                             |  |                |
    |-----------------------------+-------------------------------+-----------------------------+------------------------------------+----------------|
    | Mobility                    | none                          | Pedestrian/vehicular        | Vehicular                          | none           |
    | Message size                | Small(few Kb)                 | Medium?                     | Meduim                             | large          |
    | Traffic Pattern             | Regular                       | Regular/irregular           | Regular/irregualr                  | Regular        |
    | Device density              | Very high(10 000 per cell)    | Meduim                      | High                               | low            |
    | Latency requirements        | low(up to hours)              | Meduim(seconds)             | Very high(few ms)                  | Meduim(<200ms) |
    | Power efficency requirments | High (battery powered meters) | High(battery power devices) | Low                                | low            |
    | Relialbility                | High                          | High                        | High                               | medium         |
    | Security requirements       | High                          | Very high                   | Very high                          | medium         |
    |-----------------------------+-------------------------------+-----------------------------+------------------------------------+----------------|
    * ITS - Inteligent transportation system
    
    
*** DONE Part C (19:05) -  IoT Layers
    CLOSED: [2015-04-19 Sun 09:42] SCHEDULED: <2015-04-18 Sat>
    ▶ IoT API and Architecture
*** DONE Part D (16:08) - Interview: Dr. Adam Drobot
    CLOSED: [2015-04-20 Mon 10:28] SCHEDULED: <2015-04-20 Mon>

** Lecture 3: Network Service Pricing
*** DONE Part A (21:28)
    CLOSED: [2015-04-21 Tue 20:07] SCHEDULED: <2015-04-21 Tue>
    ▶ "Dump" pricing
    - Light users subsidizing heavy users
    - Consumers subsidizing(large) businesses
    - Bandwidth "hogs" damaging all other users
    ▶ Smart Data Prcising(SDP)
    - usage-based pricing (first problem is solved)
    ▶SDP Dimensions
    A. How to charge?
    1. Usage-based, quota rollover/trading
    2. Time/location/congestion - dependent
    3. Prepaid vs. post-paid, Contract vs no contract
    B. Whom to charge??(2-sided, 1-800, toll-free, zero rating, sponsored data, unlimited,...)
    1. Closed
    2. Open 
    C. What service are you charged from?/ Coount byte
    1. Paid Priority - queueing systems
    2. Transaction-based (instead of counting bytes, we ask have you finished, Pioners are amazon->Kindle, you oay not for bytes)
    3. Cloud service pricing 
    4. IoT service pricing
      

*** Part B (10:01)
*** Part C (11:03)
*** Part D (17:54)
** Lecture 4: Principles of P2P Networking
*** Part A (21:28)
*** Part B (10:01)
*** Part C (11:03)
*** Part D (17:54)
** Lecture 5: Client-Driven Control & Configuration
** Lecture 6: Client-based Measurement IoT Signaling
** Lecture 7: Edge Pooling and Caching
** Lecture 8: Fog/IoT Security and Privacy
** Lecture 9: Consumer/Wearable/Home IoT
** Lecture 10: Connected Cars
** Lecture 11: Smart Grids
** Lecture 12: Healthcare

